import type { Metadata } from "next";
import { Inter, Lora, Caveat } from "next/font/google";
import "./globals.css";
import Image from 'next/image';
import Navigation from '../components/Navigation';

const inter = Inter({
  subsets: ["latin"],
  variable: '--font-inter'
});

const lora = Lora({
  subsets: ["latin"],
  weight: ["700"],
  variable: '--font-lora'
});

const caveat = Caveat({
  subsets: ["latin"],
  weight: ["700"],
  variable: '--font-caveat'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${lora.variable} ${caveat.variable}`}>
      <body>
        <header className="fixed top-0 left-0 w-full bg-white shadow-md z-50 p-4 flex items-center justify-between border-b border-gray-200 h-30">
          {/* Logo IHC à esquerda */}
          <div className="flex items-center h-full w-30 md:w-40">
            <div className="relative h-full w-full">
              <Image
                src="/logo.png"
                alt="IHC Marketplace - test company"
                fill
                style={{ objectFit: 'contain' }}
              />
            </div>
          </div>
          
          {/* Navegação à direita */}
          <Navigation />
        </header>
        <main className="pt-20 md:pt-24 bg-gray-50 min-h-[calc(100vh-80px)]">{children}</main>
      </body>
    </html>
  );
}
